# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('latD', models.DecimalField(decimal_places=10, max_digits=15)),
                ('lonD', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightValue', models.IntegerField(choices=[(1, 'forward'), (2, 'backward'), (3, 'left'), (4, 'right')], max_length=1)),
                ('lightColor', models.CharField(choices=[('R', 'red'), ('Y', 'yellow'), ('G', 'green')], max_length=1)),
            ],
        ),
    ]
