# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traffic',
            name='area',
            field=models.CharField(default='New Delhi', max_length=40),
        ),
    ]
