# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='lightValue',
            field=models.IntegerField(choices=[(1, 'forward'), (2, 'backward'), (3, 'left'), (4, 'right')]),
        ),
    ]
