# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170506_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=15),
        ),
    ]
