# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_traffic_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=15)),
                ('lon', models.DecimalField(decimal_places=10, max_digits=25)),
                ('area', models.CharField(default='New Delhi', max_length=40)),
            ],
        ),
    ]
