# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170507_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='heading',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='latD',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='lonD',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
    ]
