# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170507_0154'),
    ]

    operations = [
        migrations.CreateModel(
            name='heading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.DecimalField(decimal_places=10, default=0.0, max_digits=25)),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='heading',
        ),
    ]
